---
apiVersion: v1
kind: Namespace
metadata:
  name: locust
  labels:
    name: locust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  labels:
    name: locust
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust
  template:
    metadata:
      labels:
        name: locust
    spec:
      containers:
      - name: locust
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://front-end.sockshop.svc.cluster.local -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100 --no-web; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux
