---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arh-manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list"]
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list"]
- apiGroups: ["karpenter.sh"]
  resources: ["provisioners"]
  verbs: ["get", "list"]
- apiGroups: ["karpenter.k8s.aws"]
  resources: ["awsnodetemplates"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arh-manager-role
subjects:
  - kind: Group
    name: arh-manager-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: arh-manager-role
  apiGroup: rbac.authorization.k8s.io
